### ISSUE TITLE
Option to disable console.log?

### ISSUE THREAD

**Issue by biati-digital** [apexskier/nova-extension-utils#2]
This package is great and it offers a way to easily install extension dependencies i think it could be useful a way to disable console.log as it will show the same message in the debug pane and it becomes a little annoying if you have a few extensions using this package and probably more developers will use it in the future?

It will be awesome if the extension was in charge of error logs instead of the package that way developers could have more control on this, for example i add an option to enable or disable log messages.

![Screen Shot 2020-10-07 at 11 44 31](https://user-images.githubusercontent.com/1219228/95361546-7b312d80-0892-11eb-9159-943937c53db7.png)

Anyway, just an idea, this is a really useful package.

Thank's

**Comment by apexskier** [comment]
Good feedback - I'll think a bit about what the interface for controlling this as a consumer should be.

**Comment by apexskier** [comment]
Take a look at https://github.com/apexskier/nova-extension-utils/pull/3

**Comment by biati-digital** [comment]
Awesome, that should do it. 👍
