### ISSUE TITLE
Optimise npm install

### ISSUE THREAD

**Issue by robb-j** [apexskier/nova-extension-utils#43]
Hi, thanks for publishing this package, it's been really useful getting a YAML LSP extension up and running.

Do you think it would make sense to add `--no-audit` to the `npm install` part of the setup?
It should remove some unneeded network use at the startup of Nova, especially with a few extensions using this package now.
I'm happy to submit a PR if you like.

https://github.com/apexskier/nova-extension-utils/blob/3b50d9817a57ebe40b941b304316774548a33991/src/dependencyManagement.ts#L163-L171

**Comment by apexskier** [comment]
Yes, I think this is a great idea. I'll definitely take a PR
