### ISSUE TITLE
The lockfile sometimes it's not deleted correctly

### ISSUE THREAD

**Issue by biati-digital** [apexskier/nova-extension-utils#8]
I was having problems with one of my extensions, checking the debug pane the last message displayed was "**already locked**", for some reason the lock file was not deleted when the last process ended so the file stayed there and the setInterval did nothing as there was no other process to delete that file. I know you can provide a command to clear that file but i think it's possible to fix this without user intervention.

So i propose two solutions:

1.- Not the best but maybe can be used with the second solution? So we can check when the lockfile was created, if it's more than five minutes ago then probably something went wrong.

```javascript
const created = nova.fs.stat(lockFilePath).birthtime;
const diff = new Date().getTime() - created.getTime();
const minutes = Math.round(((diff % 86400000) % 3600000) / 60000);

// it's been 5 minutes since the file was created,
// probably the lock file was not removed the last time the process
// was executed, delete and continue
if (minutes > 5) {
    nova.fs.remove(lockFilePath);
}
```

2.- When creating the lockfile we can append the process ID to that file, so next time if there's a lockfile we can grab the process ID stored in that file and check if the process is still running

So we can verify if the process is running with the following command:

`kill -0 $processid`

Calling kill with **-0** will not end the process if it exists, if a process with that ID is not found then the following error will be returned:

**kill: kill $processid failed: no such process**

So in case the process it's no longer running we can delete the lockfile and continue the process normally to avoid extensions not starting because of the lockfile left behind.

**To reproduce**

Only god knows.

**Expected behavior**

The lockfile should be deleted if there are no other processes running and was left behind.

**Comment by apexskier** [comment]
Remembering the original PID and checking if it's still running is a very good idea. I've seen this as well when crashes happen.

**Comment by apexskier** [comment]
https://github.com/apexskier/nova-extension-utils/pull/11
